FROM ubuntu:18.04
LABEL maintianer="Lisupy"
LABEL description="This is the develop docker images for uts"

RUN sed -i s@/archive.ubuntu.com/@/mirrors.tuna.tsinghua.edu.cn/@g /etc/apt/sources.list && \
    apt-get clean && apt-get update && \
    apt-get install -y \
        build-essential cmake gdb vim curl netcat locales git tcpdump \
        iputils-ping && \
    apt-get clean

RUN locale-gen en_US.UTF-8 && \
    echo 'export LANG=en_US.UTF-8' >> /root/.bashrc && \
    echo 'export LC_ALL=en_US.UTF-8' >> /root/.bashrc

WORKDIR "/root/"

VOLUME [ "/root/app", "/root/res" ]

ENTRYPOINT [ "/bin/bash" ]
